### ISSUE TITLE
Avoiding grid line which is too close to the axis

### ISSUE THREAD

**Issue by shirshendubhowmick** [airbnb/visx#1024]
Is there any simple way by which I can avoid grid line which is too close to the axis ?

Example, check the grid line for -40, it's too close to the axis

![image](https://user-images.githubusercontent.com/12836504/104637939-7cf96100-56cb-11eb-9986-3e36923ad22a.png)

I am suing `GridRows` component for rendering the grid lines and `AxisBottom` for the X axis.

**Comment by williaster** [comment]
Hey @shirshendubhowmick thanks for checking out `visx`. FYI I think this type of question would be perfect for github [discussions](https://github.com/airbnb/visx/discussions) rather than an issue.

I think this problem is more of an issue with how you've configured your axis scales. Our `@visx/scale` docs link to the underlying `d3-scale` docs which have more information about `scale` configuration. In particular I think if you pass [`nice: true`](https://github.com/d3/d3-scale/blob/master/README.md#continuous_nice) to your config it will fix the problem. `nice` attempts to apply "nice" (round) values to the min/max of the scale. 

In this case it looks like the grid lines are on even values like `-40, -30, etc` but the minimum of the scale is something like `-42`. `yScale = scaleLinear({ nice: true, ... })` would hopefully yield an even minimum (and maximum) value of `-40` or `-50` which will make the grid lines look nicer.

**Comment by shirshendubhowmick** [comment]
Hi @williaster thanks for your reply.

Adding `nice` did solve the problem a new one is introduced. Not sure if this is because `nice` or I have done something wrong. I am trying to investigate that.

![image](https://user-images.githubusercontent.com/12836504/104641279-8edd0300-56cf-11eb-8483-ca896df899ae.png)

Check the label with 10

**Comment by williaster** [comment]
It looks like it's simply getting clipped (by the `SVG` potentially). can you increase `margin.top` in your example? (not sure how you're doing this exactly but that's what I'd guess)

**Comment by shirshendubhowmick** [comment]
> Hi @williaster thanks for your reply.
> 
> Adding `nice` did solve the problem a new one is introduced. Not sure if this is because of `nice` or I have done something wrong. I am trying to investigate that.
> 
> ![image](https://user-images.githubusercontent.com/12836504/104641279-8edd0300-56cf-11eb-8483-ca896df899ae.png)
> 
> Check the label with 10

I think this problem is because `nice` is trying to have a rounded values, which is causing it to render more ticks.

But there not enough space left to render all the tick labels.

I think this is more of related to how the axis scales are defined

**Comment by shirshendubhowmick** [comment]
> It looks like it's simply getting clipped (by the `SVG` potentially). can you increase `margin.top` in your example? (not sure how you're doing this exactly but that's what I'd guess)

Yes it is clipped by the SVG. I think this can be solved in multiple ways to depeding upon how it is being used.

However will it be a good idea to provide an API by which we can specify a max number of ticks we want to redner at any point of time ?

**Comment by williaster** [comment]
From the [`@visx/axis` docs](https://airbnb.io/visx/docs/axis): `numTicks` and `tickValues`, and `tickFormat` all give you hooks to limit the number of ticks, specify their values, or to show/hide/truncate labels depending on your use case.

I'm going to go ahead and close this issue as it's more about specific usage rather than inherent bugs or limitations with `visx`, feel free to re-open if you have further questions or start a github discussion!
