### ISSUE TITLE
How to manage long tickLabels in animatedAxis ?

### ISSUE THREAD

**Issue by VigneshTrantor** [airbnb/visx#1027]
How to manage long tickLabels in animatedAxis ?
![long names](https://user-images.githubusercontent.com/73022493/105023209-ad951e00-5a70-11eb-9656-35ca1069c65d.png)

**Comment by williaster** [comment]
Hey @VigneshTrantor thanks for checking out `visx`. I think this question is more fit for [discussions](https://github.com/airbnb/visx/discussions) since it's not an issue, it's ultimately a question about usage and design.

Feel free to start a new discussion, or see [my answer in this similar question](https://github.com/airbnb/visx/discussions/1000#discussioncomment-270284).
