### ISSUE TITLE
[Bar Chart] Set max width of a bar

### ISSUE THREAD

**Issue by wisyr** [airbnb/visx#1032]
tl;dr - Is there a way to set a max width of a bar in charts but still keep it dynamic? 

The issue is related with bar width. If there's enough of data, a single bar looks just okey.
![image](https://user-images.githubusercontent.com/20928453/105636114-f846d980-5e66-11eb-80a7-9254941d70b2.png)

But if there's no enough data, the bars are getting too wide.
![image](https://user-images.githubusercontent.com/20928453/105636160-4065fc00-5e67-11eb-9e64-55ca3268a6fe.png)

Is there a way to somehow set a max width of a single bar? But still keep it dynamic so it is responsive when chart is resizing.

Playground: https://codesandbox.io/s/holy-pine-i5sp2?file=/Example.tsx

Thank you for such an outstanding library!

**Comment by williaster** [comment]
Hey @wisyr thanks for checking out `visx`! We recently enabled [`discussions`](https://github.com/airbnb/visx/discussions) on this repo to help with usage questions versus actual issues with `visx`.

I'm going to go ahead and move your question over there because I think it's more about usage, but feel free to re-open this if you think it's an issue with `visx`!
