### ISSUE TITLE
[XYChart] Add `padding` property `<BarStack>`

### ISSUE THREAD

**Issue by valtism** [airbnb/visx#1041]
[Feature Request] 

Would love for `<BarStack>` to have feature parity with `<BarGroup>` by allowing us to specify a padding.

Even better would be if we could specify a specific (or max) bar width in pixels, to maintain bar size across different sized charts.

**Comment by williaster** [comment]
Hey @valtism thanks for the request. Can you be a little more specific about what you're envisioning here? 

If you mean the distance **between stacks**, this is controlled with the `xScale` config passed to `XYChart` for `band` type scales:

`xScale={{ type: 'band', paddingInner: 0.8 }}`
<img src="https://user-images.githubusercontent.com/4496521/106661596-3a9ea380-6556-11eb-84e2-0cb2564b5e39.png" width="500" />

`xScale={{ type: 'band', paddingInner: 0.3 }}`
<img src="https://user-images.githubusercontent.com/4496521/106661649-4d18dd00-6556-11eb-8488-3a96bb55b76a.png" width="500" />

If instead you are referring to the _**distance between bars within a stack**_ (analogous to space between bars within a `BarGroup` group), this is not supported as there is no `d3` equivalent. I think this doesn't exist because if you were to add random space between the bars in the stack, the y-axis would become meaningless.

Not sure if you're going for style here, but if so you could probably accomplish this with a `stroke`/`strokeWidth` set for each bar `rect` (note that this preserves the accuracy of the chart for the most part). Looks like the props for this don't work right now but you can set it with CSS / here's a proof-of-concept:

<img src="https://user-images.githubusercontent.com/4496521/106662571-65d5c280-6557-11eb-9d15-292768394c77.png" width="500" />
 

> Even better would be if we could specify a specific (or max) bar width in pixels, to maintain bar size across different sized charts.

We mostly mirror the `d3` syntax for scales because they are already quite complex, and it makes a 1:1 mapping for those coming from `d3`. If you'd like to create a constant bar width across dynamic chart sizes, see my answer to [this discussion question](https://github.com/airbnb/visx/discussions/1035).

**Comment by valtism** [comment]
Wow, super detailed reply. Thank you!

Yes, I was referring to the band padding. I saw something mentioning it on the `<BarGroup>` `padding` docs, it didn't click that it would also work for the `<BarStack>`.

The space between bars is also very useful for me. I think that using a stroke would be perfectly fine, as the look of the charts is more important in our use-case than complete accuracy.
