### ISSUE TITLE
[visx/tooltip] Wrong positioning of TooltipInPortal

### ISSUE THREAD

**Issue by AKolodeev** [airbnb/visx#1051]
Hi folks,

Thank you for such a nice library, I am really enjoying using it 🔥 

However, I faced an issue with TooltipInPortal which you can observe here: https://codesandbox.io/s/dazzling-wave-q2ihl?file=/src/App.js. Just click at both points.
The click on the right top point works as expected and opens a tooltip left to the point, but the click on the left bottom point works strange because it opens a tooltip bellow the svg element.

I tried to debug this behaviour and here is what I found:
1. In TooltipWithPortal, containerRef.current === the expected SVGElement - OK
2. TooltipInPortal correctly renders TooltipWithBounds - OK
3. But TooltipWithBounds receives the bounds of the parent element, i.e. div which is rendered by TooltipWithPortal and not the bounds of the svg element - Not OK

Could you please advice me something? Or just confirm that it is visx's bug and I could try to fix it with a PR.

Here are my deps:
```
"@visx/event": "^1.3.0",
"@visx/shape": "^1.4.0",
"@visx/tooltip": "^1.3.0",
```

**Comment by williaster** [comment]
Hey @AKolodeev  👋  thanks for checking out `visx`. As far as I can tell `TooltipInPortal` is behaving as designed. Because it is rendered in a `Portal` (i.e., a `div` appended to `body`), it's container bounds are the page bounds which means that it will be visible outside and on top of the chart container where you render it.

You can check this by making the window size small in your sandbox, when there is not enough space below the container to render the tooltip, it renders inside it.

![image](https://user-images.githubusercontent.com/4496521/107439048-5241d300-6ae6-11eb-97bb-5c3dc98ef015.png)

If you want the tooltip to be contained inside it's chart container, I would suggest using `TooltipWithBounds` on its own. This will detect the container bounds and move left/right or top/bottom depending on space. Here's a [modified sandbox](https://codesandbox.io/s/holy-browser-40891). I would also suggest playing around with the [Tooltip demo](https://airbnb.io/visx/tooltip) which allows you to toggle on / off rendering in a portal and demonstrates the different types of behavior that are possible.

![image](https://user-images.githubusercontent.com/4496521/107439360-c8ded080-6ae6-11eb-8fa7-cf5a883ab18c.png)

**Comment by AKolodeev** [comment]
Hi, Chris! Thank you very much for your advice :)

It helped, so I'll close the issue.
