### ISSUE TITLE
Animate pathLength of chart with Framer Motion

### ISSUE THREAD

**Issue by MaximeHeckel** [airbnb/visx#1055]
Hi 👋

First of all, I love visx and I think the approach you took with this library is the best: little opinionated, still higher level than raw D3.

I'm doing a couple of little experiment trying to integrate visx with framer-motion, it works perfectly, however, I'm struggling with the following:
I would like my `AreaClosed` chart to "draw" itself on render (from left to right), and for that I'd usually base my animation on the `pathLength` attribute of the `<path/>` element when using Framer Motion:

```js

const MyChart = (props) => {
   const pathVariants = {
      initial: {
        pathLength: 0,
      },
      animate: {
        pathLength: 1,
      },
    };

    const pathLength = useMotionValue(0); 

  return (
      <svg width={width} height={height}>
          <AreaClosed
            data={formattedData}
            x={...}
            y={...}
            yScale={...}
            curve={curveMonotoneX}
          >
            {(area) => (
              <g>
                <motion.path
                  d={area.path(formattedData)}
                  initial="initial"
                  animate="animate"
                  stroke="url(#hr)"
                  variants={pathVariants}
                  fill="url(#hr)"
                  style={{ pathLength }}
                />
              </g>
            )}
          </AreaClosed>
      </svg>
  )
}

```

Also I noticed that setting the `pathLength` attribute manually does not work either.

Do you know if it's possible to achieve the desired effect with Framer Motion? Since it's my only "animation library" on my project I'd really want to avoid introducing something different for charts if possible 

Thank you in advance for your help!

**Comment by MaximeHeckel** [comment]
Ok I think I got something that's almost there but not quite:

1. I was able to get a "drawing" animation by getting inspired by the LineRadial example in your docs: https://airbnb.io/visx/lineradial

Instead of `react-spring` I actually figured out a way to make it work with Framer Motion: I needed to set the `strokeDasharray` and `strokeDashoffset` attributes instead of the `pathLength`:

```js
{(area) => (
      <g>
        <motion.path
          d={area.path(formattedData)}
          initial="initial"
          animate="animate"
          stroke="url(#hr)"
          variants={pathVariants}
          style={{
              strokeDashoffset: pathLength,
              strokeDasharray: pathLength,
            }}
        />
      </g>
    )}
```

![chart](https://user-images.githubusercontent.com/2974412/107458143-81c20100-6b21-11eb-8e85-3ac9e94b434e.gif)

2. Somehow I can't manage to make this happen at "mount" time. I can only make the animation happen by toggling a state. Without toggling a state the chart simply renders immediately without triggering the animation. Not blocking just a bit weird. Do you have more info on that? 

3. This worked well for the line, the *filled* part of the chart is not animated I guess that's just not possible as is (I'd basically want the *filled* part of the area chart to grow from left to right while following the line). Will need to continue tweaking

**Comment by williaster** [comment]
Hey @MaximeHeckel 👋  thanks for checking out `visx`. Since this is a usage question rather than an issue, I'm going to move it over to our github discussions. I'm not super familiar with `Framer Motion`, but we do have an example of animating a line path in our [radial line example](https://airbnb.io/visx/lineradial) using `react-spring`, which you just posted as I was typing this 😄  

I'm not familiar with the `pathLength` approach you were trying to use initially, but the `lineDasharray` is the most common solution I've seen for animating lines. However SVG areas paths often have circular shapes (e.g., closed areas basically draw a big circle to close on themself) so I'm not sure you will actually be able to do what you're envisioning by animating the path this way. For advanced animation/tweening like that, you may need to rely on custom interpolators which can interpolate the `path`'s `d` string better. In our `@visx/xychart` library [we use `d3-interpolate-path`](https://github.com/airbnb/visx/blob/master/packages/visx-xychart/src/components/series/private/AnimatedPath.tsx#L26) to interpolate between new data or changing numbers of points (it doesn't sweep across as in your example, see the demo [here](https://airbnb.io/visx/xychart) to play with the animation), but you could consider [`flubber`](https://github.com/veltman/flubber) which is made for closed shapes (still not sure you could sweep like you want.

Given all of the complexity described above^, I wonder if it would be simpler for you to animate a `rect` (maybe as a clip-mask) if you simply want to reveal the line. Depending on how you do it that should just involve animating a width from `0 => width` or `width => 0`.

Re the animation not working upon mount, it might because of two successive renders which happen very quickly. For the 1st render, you would maybe be interpolating from `0 => value` but on the second render you would be interpolating `value => value`. We faced this issue in `@visx/xychart` and [solved it by debouncing](https://github.com/airbnb/visx/blob/master/packages/visx-xychart/src/components/series/private/AnimatedPath.tsx#L15) the calls.
