### ISSUE TITLE
scaleLinear returns invalid value for domain = [0, 0]

### ISSUE THREAD

**Issue by zouxuoz** [airbnb/visx#1070]
Looks like `scaleLinear` returns invalid value for `domain` = [0, 0]

Use case: when all values on the chart equals 0

Current behaviour:

```js
scaleLinear({ range: [100, 0], domain: [0, 0] })(0); // returns 50
```

![image](https://user-images.githubusercontent.com/9217163/108187790-e5e75500-711f-11eb-8473-d31e32bd72e0.png)

Expected behaviour:
```js
scaleLinear({ range: [100, 0], domain: [0, 0] })(0); // returns 0
```

**Comment by williaster** [comment]
Hey @zouxuoz 👋  thanks for checking out `visx`. This actually isn't a `visx` issue, and it is intentional behavior from the underlying `d3-scale` for "collapsed domains" (where `start === end`).

This is similar to visx issue #473 with a suggested workaround, and ultimately you can see the `d3-scale` issue/fix [here](https://github.com/d3/d3-scale/issues/117).
