### ISSUE TITLE
BarRounded with AnimatedBarSeries and XYChart

### ISSUE THREAD

**Issue by tonyneel923** [airbnb/visx#1092]
Is this possible with Bar Series or do we need to create our own shape?

**Comment by tonyneel923** [comment]
Here is a sandbox that explains what I mean -> https://codesandbox.io/s/exciting-pond-2p28d?file=/Example.tsx:3133-3164

I have a BarSeries commented out that worked perfectly but the rectangles are not rounded. I added my own bars but it removed the grid and axis.

Sorry if this is not the correct place to ask. Thanks for any help.

**Comment by williaster** [comment]
Hey @tonyneel923 👋 , currently we don't expose the BarRounded in the `@visx/xychart` package. We probably could add this pretty easily but I'm not sure I'll have the bandwidth to do it myself soon. For now I'll label this as help wanted and am happy to 👀  a PR.

I'm not sure what aesthetics you're going for with the bars, but you can use `css` to set `rx/ry` to give something like this ([sandbox](https://codesandbox.io/s/relaxed-bose-ljko6?file=/Example.tsx)):

<img src="https://user-images.githubusercontent.com/4496521/109734503-f4009100-7b75-11eb-9e6d-f9b72deb837a.png" width="500" />

It's not quite the same since all 4 corners are rounded, but might be a quick workaround until this gets added.

**Comment by tonyneel923** [comment]
Thanks for the guidance @williaster. I am just starting to vet this library so I was unsure what was possible. I will definitely look into the code of visx soon if this is not added and see if I can help out.

Great library and thanks again!

**Comment by tonyneel923** [comment]
I decided to take a stab at this. It does not seem to complicated like you mentioned but I am having some issues with the type for BarsComponent. I do not have very much experience in Typescript but it seems like it should not be erroring. Curious if you can unstick me real quick.

![image](https://user-images.githubusercontent.com/5866014/110020285-a0618500-7ce6-11eb-8d51-ecf24d3c4daf.png)
![image](https://user-images.githubusercontent.com/5866014/110020383-b7a07280-7ce6-11eb-80b9-c92e4384243f.png)

**Comment by tonyneel923** [comment]
I was able to fix the above by sticking BarsComponent in SeriesProps but that is obviously not what I want to do.

**Comment by williaster** [comment]
Hey @tonyneel923 sometimes it can be pretty hard to debug types from screenshots. Do you have a branch I can pull? Just from looking at it this matches `BarSeries` as it stands already, did you update the `/private/Bars` component?

**Comment by tonyneel923** [comment]
No but I did figure out that I can cast the prop but not sure if it is the right idea. I will push up my branch so you can look at it. Thanks for the help.

**Comment by tonyneel923** [comment]
https://github.com/tonyneel923/visx/tree/feature/support-any-shape-xychart

**Comment by tonyneel923** [comment]
Current Branch works if you look at example select bars and remove animated component

**Comment by williaster** [comment]
Thanks for pushing it. Ah I see, so you would allow overriding of the `BarsComponent`. In thinking about this a little more, there was also a request for this functionality for `BarStack` (and therefore probably `BarGroup`) in #1093. So I'm wondering if instead we should actually bake in some of the props from `BarRounded` rather than requiring full component overloading.

I think it'll be a bit tricky to do this in a way that's not a breaking change (i.e., only use the `BarRounded`/`<path />` if a `radius` is specified, else continue to use `<rect />` because if people are using a `rect` in css selectors it would break). Given that complexity I'm happy to take a shot at implementation. I think I should be able to get it out by tomorrow unless you still want to take a shot! lmk :)

**Comment by tonyneel923** [comment]
I appreciate the quick help and guidance. I am fine with you taking over since you know more of the context with both the problem and the code.

One minor note though I chose this approach because it gives the most flexibility. If say I wanted to use a different shape than bar rounded for bar charts? It would be nice to be able to use XYChart as a helper still but also have the flexibility of passing in whatever shape I wanted. 

Either way though if this is not desired behaviors for others that is fine I just figured it would be an elegant escape hatch.
