### ISSUE TITLE
Publish code for `@visx/text` demo

### ISSUE THREAD

**Issue by maltebaer** [airbnb/visx#1244]
Hi,

in [this article](https://medium.com/airbnb-engineering/introducing-visx-from-airbnb-fd6155ac4658) you show a preview of a feature I would love to implement 😍 and reference to [a codesandbox](https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-text). Unfortunately the link is broken because the examples does no longer exist in your repo.

Is it possible to publish the code again?

Many thanks in advance!
Malte

**Comment by williaster** [comment]
Hey @maltebaer 👋  thanks for checking out `visx`. Apologies for the broken link, the `visx` `@visx/text` demo can be found on the demo site [here](https://airbnb.io/visx/text) (it's not implemented as an independent sandbox which is why the link is broken), however it's **not** the same one as the image in the site. 

That image comes from my [`data-ui` project](https://williaster.github.io/data-ui/?selectedKind=xy-chart&selectedStory=TickLabelPlayground&full=0&addons=0&stories=1&panelRight=0) (source [here](https://github.com/williaster/data-ui/blob/master/packages/demo/examples/01-xy-chart/TickLabelPlayground.jsx)). `data-ui` is implemented with `visx` primitives, so everything you see there should be possilbe (and is maybe more clearly illustrated in the `@visx/text` demo I linked to above.

**Comment by williaster** [comment]
Going to close this as I believe it's resolved but feel free to re-open if you disagree.

**Comment by maltebaer** [comment]
Hey @williaster thank you so much for providing the examples. The [`TickLabelPlayground`](https://williaster.github.io/data-ui/?selectedKind=xy-chart&selectedStory=TickLabelPlayground&full=0&addons=1&stories=1&panelRight=0) is exactly what I was looking for.

By the way: I'm really curious about where `xychart` is going. it looks really promising. Keep up the great work!
