### ISSUE TITLE
Path tag in geomap does not trigger onclick

### ISSUE THREAD

**Issue by dinaandrei** [airbnb/visx#1248]
In the example for geomap found here: https://airbnb.io/visx/geo-custom, the onClick on the path (aka the country) does not do anything. I would also like to hover over the country and change the color but that doesn't seem to work as well

**Comment by iampueroo** [comment]
Hey @dinaandrei! The code is a bit misleading. There [is a `<rect>` element](https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-geo-custom?file=/Example.tsx:3609-4218) that is intercepting all mouse events which handles the drag events, so the `<path>`s are not actually being clicked. Removing the `<rect>` makes everything work as you expect. It might also work to change the DOM structure so that the click event can bubble up from the paths so both events fire (or change how the dragging is implemented 🤷).

It looks like that `alert()` line was just accidentally left over from the previous iteration of that example in [this commit](https://github.com/airbnb/visx/commit/686eb01e1f2dfd10240f56ddcaa98196b0315116#diff-35814c61f1bb4125528f8750d1d547e42857b77c1cd5f0a6889b2aaf8aa3825eR114-R124). I'll let @williaster chime in regarding if the alert _should_ work. I would argue it should just be removed - the demo seems to be more focused on dragging/zooming at this point.

**Comment by hshoff** [comment]
Hi @dinaandrei, yes what @iampueroo said is correct. The events are being intercepted in the demo. Adding click handlers to paths should work as expected.
