### ISSUE TITLE
[@visx/xychart] Missing react-spring dependency

### ISSUE THREAD

**Issue by schillerk** [airbnb/visx#1265]
Minimal reproduction
`npx create-react-app visx-demo`

Replace App.jsx with the demo here:
https://airbnb.io/visx/docs/xychart

`Module not found: Can't resolve 'react-spring' in '/Users/kyleschiller/src/xychart-demo/node_modules/@visx/react-spring/lib/axis'`

after `npm i react-spring`, issue is resolved.

**Comment by williaster** [comment]
Hey @schillerk , thanks for filing the issue 🙏  I don't think this is actually a problem, though, since we declare `react-spring` as a `peerDependency` in the `@visx/xychart` `package.json`:

https://github.com/airbnb/visx/blob/fbbaf42ca8cd56f8fd8ef53ed8799e31fbffb0b9/packages/visx-xychart/package.json#L40

The `peerDependency` indicates that package consumers need to install that dependency themselves. If you do that it should work as you noted, and here's the working sandbox that the `xychart` demo links to https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-xychart?file=/package.json:535-566

**Comment by schillerk** [comment]
Got it, thanks for the clarification!

**Comment by TrySpace** [comment]
I first had `'to' is not exported from react-spring`. Tried removing nodes_modules & reinstalling, no avail.

Then updated to `9.3.2`, then the error went away. However, now `react-spring/web.cjs` is not available, but lulckily I don't care about IE11
