### ISSUE TITLE
codesandbox.io is failing

### ISSUE THREAD

**Issue by timurcatakli** [airbnb/visx#1287]
https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-axis

![image](https://user-images.githubusercontent.com/15508978/126598399-91104de9-bb9c-442c-80f3-96a5d14d27a2.png)

Thank you,

**Comment by williaster** [comment]
Hey @timurcatakli 👋  thanks for checking out `visx`. 

this is because we just did an alpha release so the `latest` packages installed in the code sandbox examples aren't consistent with the code that's in the sandbox. this should be fixed once we release the actual `2.0.0`, but as a workaround you should be able to change any `@visx/react-spring` or `@visx/xychart` deps from `'latest'` to `'next'`. 

[here's a workaround](https://codesandbox.io/s/pensive-sound-3y570?file=/package.json) for the one you linked to.

**Comment by jwlms** [comment]
I'm not sure if this is the same issue (it looks like you're on v2.9 now), but the sandbox links from the gallery don't seem to be working. I followed the link here https://codesandbox.io/s/github/hshoff/vx/tree/master/packages/vx-demo/src/sandboxes/vx-geo-mercator directly from this page: https://vx-demo.vercel.app/geo-mercator and it doesn't seem to load a project at all.

Do you have any work arounds for this?

**Comment by williaster** [comment]
Hey @jwlms I think you may be using the legacy / deprecated project site (`vx`, not `visx` which was migrated into the airbnb github account). The new link for that example is https://airbnb.io/visx/geo-mercator, which is linked to from the current [gallery](https://airbnb.io/visx/gallery) specified in the project readme.

**Comment by williaster** [comment]
this should no longer be an issue since we have a stable release out.

**Comment by jwlms** [comment]
You are correct, thanks for pointing me to the correct url!
