### ISSUE TITLE
remove stroke left and right

### ISSUE THREAD

**Issue by callmejm** [airbnb/visx#1309]
![image](https://user-images.githubusercontent.com/6957533/128992426-05a58514-5f74-40d0-88c6-640f446cbc7a.png)

How to remove stroke left and right

**Comment by williaster** [comment]
HI @callmejm  👋  thanks for checking out `visx`. this is a usage question so I would generally open a [discussion](https://github.com/airbnb/visx/discussions) for this type of thing in the future since it's not an issue.

a similar question was recently asked in https://github.com/airbnb/visx/issues/1274 where I gave an answer, so I'm going to close this for now as a duplicate.
