### ISSUE TITLE
Zoom - Single tick of wheelEvent generates scale twice

### ISSUE THREAD

**Issue by ronlv10** [airbnb/visx#1382]
Single tick spin of the mouse wheel zooms the view two times. 

This is happening in the zoom demo : https://airbnb.io/visx/zoom-i, see : https://www.loom.com/share/da8e96389cfe40939d59d8ad71d53313

Tried to use onWheel to track the events and got a single invocating, but debugging the handleZoom function shows that is called twice: logged the events here : 
https://pastebin.com/EDifzZXM

**Comment by nikostri** [comment]
I am also seeing this. The issue appears to be the result of code from `@use-gesture`, specifically in `WheelEngine.ts`:
https://github.com/pmndrs/use-gesture/blob/374b87e043030c0927de9eb609149b3156b5bc5b/packages/core/src/engines/WheelEngine.ts#L29
```js
wheelEnd() {
    if (!this.state._active)
      return;
    this.state._active = false;
    this.compute();
    this.emit(); // <- This line is causing the issue
  }
```
The reemission of the wheel event on "wheel end" is causing it to get triggered one extra time at the end, and sometimes that extra call can result in very unexpected zoom values (I think because of the rubberbanding calculations?).
