### ISSUE TITLE
Tooltip not showing at last datapoint

### ISSUE THREAD

**Issue by basslagter** [airbnb/visx#1472]
Showing me the second to last:
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/6328997/163184448-08f3db81-369b-46ed-b0da-8c4d8a60ad9d.png">

But when I move to the right and hovering the last datapoint (for any of the three lines) it is not not showing the tooltip.

I'm using the XYChart component and LineSeries and Tooltip. Is this 'normal' behaviour?

**Comment by hshoff** [comment]
Hi @basslagter this looks similar to https://github.com/airbnb/visx/issues/1806#issuecomment-2016319358. This would be the expected behavior for an x scale using `point`. I'd recommend switching the x scale to `time` and pass in Date objects and adjust the x axis number of ticks accordingly. Thanks for checking out visx.
