### ISSUE TITLE
EditableAnnotation width prop seems not to be working 

### ISSUE THREAD

**Issue by gracelauren** [airbnb/visx#1539]
Even when you specify a width of the EditableAnnotation it does not seem to do anything. 

Check out an example of in this sandbox:
https://codesandbox.io/s/pricing-chart-proto-forked-zh1pbn

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/10436731/178801242-545d2c90-fbb1-430a-b6b2-2503a86d7c29.png">
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/10436731/178801299-3222ca39-dc57-41e7-839d-28a5a72abafe.png">
<img width="691" alt="image" src="https://user-images.githubusercontent.com/10436731/178801817-321622e4-554f-44f8-b897-03a569a39b01.png">

Separately, is there a way to prevent the selector circle from being at the very top on first load? Or a way to style this?
<img width="668" alt="image" src="https://user-images.githubusercontent.com/10436731/178801732-f775ea4e-81e5-4748-8904-a924ad98bd94.png">

**Comment by williaster** [comment]
Hi @gracelauren thanks for checking out `visx`. I'm not sure what you mean by "has no effect," as the docs specify the `width` prop for an `EditableAnnotation` determines the width of the drag area. In your example, the dragging is very buggy and starts/stops at random positions. I think this is due to the width being smaller than the chart, if you change it to `width={innerWidth}` it is much smoother. 

also, as specified in the docs, setting `y` on the `EditableAnnotation` controls the position of the subject. 

here's an updated sandbox with both, hope that helps
https://codesandbox.io/s/pricing-chart-proto-forked-b4nlpq
