### ISSUE TITLE
Better documentation enhancements

### ISSUE THREAD

**Issue by baoskee** [airbnb/visx#1545]
Hello, it's really difficult to get around the documentation. I actually love TailwindCSS's docs with the command bar. Do you allow contributions to the Documentation? I don't see any info for that on the `CONTRIBUTING.md`.

**Comment by williaster** [comment]
Hey @baoskee 👋  thanks for checking out `visx` and the interest in documentation! We made some big improvements to documentation for the `1.0` release but have not made substantial improvements since then – tho we continue to get feedback that it's not as good as it could be which I agree with.

We are definitely open to contributions to documentation! The primary considerations for me are
- **design**: documentation involves more design work than e.g., adding functionality to a package or fixing a bug, and we may have opinions on design direction. therefore it might be useful to align on the proposed design changes through mocks or prototypes (can discuss more in this issue?) ahead of a PR.
- **completion of work**: depending on the extent of documentation changes, there might be a lot of refactoring/changes. it might be best to group these into a single PR or merging multiple PRs into a feature branch, rather than merging partially finished work into master on the off chance the work cannot be fully finished.

would love to discuss more! 💜

**Comment by baoskee** [comment]
Hey @williaster yes! I would love access to the codebase for the docs. I like to work in the code and it should be really quick fixes since the website is already great. 

For big changes, I can send you links to Figma files?

**Comment by williaster** [comment]
Yes figma is great! 

The codebase for the docs is in the monorepo, the [`visx-dev/`](https://github.com/airbnb/visx/tree/master/packages/visx-demo) directory/"package". So to play around you can just 
1) fork the repo
2) run `yarn` in the root to install all project deps
3) run `yarn dev:demo` in the root (equivalent to `cd packages/visx-demo/ && yarn dev`) to start the `next.js` dev server which you can find on `localhost:3000`

**Comment by baoskee** [comment]
Ok sounds good. I'll play around and submit a draft PR. Thanks!

**Comment by hshoff** [comment]
Closing this for now. Happy to reopen in the future
