### ISSUE TITLE
docs API section is not available

### ISSUE THREAD

**Issue by N1gma** [airbnb/visx#1611]
https://airbnb.io/visx/docs API section everywhere is not displayed anymore

**Comment by williaster** [comment]
Thanks for reporting this @N1gma , most certainly due to this big TS refactoring that just happened as we generate docs from the types 😞  https://github.com/airbnb/visx/pull/1609

I just took a quick look and couldn't figure out an immediate fix. Will try to take another look but am about to be on holiday for a bit. If anyone feels like debugging https://github.com/strothj/react-docgen-typescript-loader feel free ❤️
