### ISSUE TITLE
TooltipWithBounds positioning

### ISSUE THREAD

**Issue by maximekl** [airbnb/visx#1676]
Hello,
Not sure if it's an issue or a discussion, but `TooltipWithBounds` is a blackbox kind of things, didn't find how to change this behavior.

My problem is, `TooltipWithBounds` change `tooltipLeft` but not with the best position possible : i was thinking it will stick to the right, but it's bounced back : 

Last good position (year 2039): 
```html
<div class="visx-tooltip" style="top: 0px; left: 0px; position: absolute; transform: translate(600px, 0px);"></div> 
```
And the next (year 2040) : 
```html
<div class="visx-tooltip" style="top: 0px; left: 0px; position: absolute; transform: translate(407px, 0px);"></div>
```

Here the relevante part of the code : 

```js
let tooltipStyles = {
  ...defaultStyles,
  padding: "15px",
  backgroundColor: "#5D66EB",
  color: "white",
  borderRadius: 2,
};

<div className="barchart" id={`container-${id}`} style={{ position: "relative" }}>
  <ScaleSVG xOrigin={0} yOrigin={0} width={width} height={height}>
    barStack.bars.map((bar) => (
      <BarRounded
        ...
        onMouseOver={(event) => {
          ..
          showTooltip({
            tooltipData: bar,
            tooltipTop: 0,
            tooltipLeft: bar.x,  // can use yearScale(bar.data.year) with same behavior
          });
        }}
      />
    );
  </ScaleSVG>
  {tooltipOpen && tooltipData && mode !== null && (
    <TooltipWithBounds
      key={Math.random()}
      top={tooltipTop}
      left={tooltipLeft}
      style={tooltipStyles}
      offsetLeft={0}
      offsetTop={0}
    >
      <b>content here</b>
    </TooltipWithBounds>
  )}
</div>
```
https://user-images.githubusercontent.com/11152214/226926487-e20fb10e-32d8-4544-87c8-8f516541a201.mov

1. When we hit year 2040 the behavior change and didn't stick to the nearest position (sticking right)
2. And you can see the position of the `tooltip` seem like to glide on the position (with the dotted line)

**Comment by williaster** [comment]
Hi @maximekl `TooltipWithBounds` is only meant to flip horizontally/vertically if there is not enough space to the bottom or right of the tooltip. However you can see in your video that the tooltip starts to drift relative to the vertical line, which shouldn't happen. I would try removing your `offsetLeft=0` and see if that fixes it, otherwise if you can link to a code sandbox to repro that would be useful.

there are many tooltip alignment algorithms, if you want it to appear more "stable" you could for example use `Tooltip` and simply position it to the right of the bar/vertical line if `x <= width / 2` and to the left of the bar/vertical line if `x > width / 2`

**Comment by williaster** [comment]
going to close for now.

**Comment by maximekl** [comment]
Thanks for the reply, i will use `Tooltip`instead :)
