### ISSUE TITLE
Threshold with stroke

### ISSUE THREAD

**Issue by darrylyeo** [airbnb/visx#1703]
When applying `stroke` / `strokeWidth` to `<Threshold>`'s `belowAreaProps` or `aboveAreaProps`, half of the stroke "peeks" through the clip path along the middle side (and left and right sides).

Example modification to the [New York / San Francisco temperature chart](https://airbnb.io/visx/threshold):

```tsx
<Threshold
  ...
  belowAreaProps={{
    fill: 'violet',
    fillOpacity: 0.4,
    stroke: 'purple',
    strokeWidth: 4,
  }}
  aboveAreaProps={{
    fill: 'green',
    fillOpacity: 0.4,
    stroke: 'greenyellow',
    strokeWidth: 4,
  }}
/>
```
![airbnb io_visx_threshold (1)](https://github.com/airbnb/visx/assets/13970789/e4be22da-6544-4be4-87e7-809f7f3d2d70)

Can the stroke be applied to only the top side of the "above area" and the bottom side of the "below area"? Ideally this would be done just with `<Threshold>`'s built-in props and we would not have to manually add an extra `<LinePath>` or `<SplitLinePath>` as the default example currently implies.

**Comment by williaster** [comment]
hey @darrylyeo thanks for checking out `visx`. there currently is no way to do this except with the extra `<LinePath />`s as you mention. this is due to a limitation with the `SVG` area shapes where the `stroke` is applied around the entire path.

I think it would be messy to extract `...AreaProps` and infer whether someone wants to render an extra line (what if someone actually wanted a `stroke` around the entire shape?). maybe it would be cleanest to add an `aboveLineProps` and `belowLineProps`, and if those are defined we could render the extra `<LinePath />` for consumers. I don't have bandwidth to add this but happy to review a PR if someone else is interested!

**Comment by darrylyeo** [comment]
Adding `aboveLineProps` and `belowLineProps` seems like the right way to go!

**Comment by hshoff** [comment]
Adding the additional `<LinePath>` aligns most closely with the visx philosophy of small composable primitives and would be my recommended approach for this specific use case. Going to close this for now but if there's something that comes up making the approach problematic, happy to reopen and revisit. Thanks for checking out visx.
