### ISSUE TITLE
scroll appears when drawing xychart using LineSeries but doesn't when using AreaStack

### ISSUE THREAD

**Issue by erandr** [airbnb/visx#1787]
When using LineSeries and hovering tooltips from left to right you will notice horizontal scroll appear, when using AreaStack the scroll doesn't show. The scroll shouldn't appear in both cases.

![image](https://github.com/airbnb/visx/assets/4994591/15f837b4-5e66-48b1-a20a-33138c9791f2)

**Comment by hshoff** [comment]
Hi @erandr thanks for reporting. I can't reproduce this behavior in Chrome v124. What browser and version are you seeing this?

**Comment by hshoff** [comment]
Hi @erandr closing as we haven't heard back. Happy to reopen as needed.

**Comment by jacesimons14** [comment]
@hshoff I searched and was able to find this ticket, bec I'm seeing the same 'issue' (if you can even call it that, it's really super minor) in my implementation of the xychart, so it's not just the demo on the visx docs, and I have some more information that might help narrow down the cause:

What is happening is that when you **hover over the graph** and therefore the **tooltip is rendered**, these vertical and horizontal scroll bars appear on the page. If you try to scroll, it kinda shakes the page up and down for a few miliseconds, causing your cursor to move, hence closing the tooltip, and removing the scrollbars. 
In other words, **the scrollbars are only visible when the tooltip is open**.
Importantly, this happens with any graph setups where the tooltip snaps to the datum: line, area, and bar, and grouped bar, and NOT in setups where the tooltip floats freely: **stacked** area and **stacked** bar.

I was actually not able to replicate @ erandr's issue with it on the demo in the visx docs (https://airbnb.io/visx/xychart), which is making me think the problem only arises when the graph takes up a sufficient amount of the page. In my own implementation, the chart takes up a solid ~80% of the horizontal and vertical space of the page, and in @ erandr's screenshot from the original issue above, it looks like their screen size is such that the demo chart takes up a big amount of the page as well, so that might be something to consider.

This is barely a problem because if you do scroll, it doesn't really let you go anywhere, it's just annoying. I wonder if there's an overflow property or something that needs to be enabled? Let me know if there's anything else that might help diagnose this, or if it's not important enough to move forward haha

**Comment by wildseansy** [comment]
I am also experiencing this issue. It's mainly a problem when the chart is at the very bottom of the page, because it gives your page the jitters.

**Comment by skeelin** [comment]
> ...not to mention someone put `overflow="visible"` attribute on SVG tag 🤦‍♂️

Definitely an oversight but should be something that should be easily correctable.  I have run into a number of issues with this library, but I do appreciate the level of customizations compared to others like tremor.  I just wish the documentation was a bit better and some of the bugs were fixed haha!  I briefly tried Recharts too but the level of customization just wasn't where I needed it.  Its possible that I didn't spend enough time on it and I may go at it again in the future.  In the meantime though, visx and tremor look the best and those are the two I'm trying to make work.
