### ISSUE TITLE
 Nearest datum bug in XYChart

### ISSUE THREAD

**Issue by RamonEspinosa** [airbnb/visx#1806]
# Nearest datum bug in XYChart
## Description
The XYChart and some components included in `@visx/xychart` fail to find the nearest datum when hovering over the chart. It looks like it always finds the nearest datum that is to the left of the user's cursor. 

## Expected behaviour

The `onPointerDown`, `onPointerMove`, `onPointerOut`, `onPointerUp` callbacks should have access to the datum that is the nearest to the user's cursor.
The same is true to some components that make use of the nearest datum like `Tooltip` (see [renderTooltip](https://airbnb.io/visx/docs/xychart#Tooltip_renderTooltip)).

## Reproduction link
https://codesandbox.io/p/sandbox/visx-nearest-datum-bug-2nym26

## Screenshots
Here, you can see that even though the cursor is close to the second datum, the XYChart thinks the nearest datum is the first datum.
![image](https://github.com/airbnb/visx/assets/47266830/bba2325b-e25f-4513-8ea6-e0db904f9d41)
Notice how the last datum is never found as the nearest to the user's cursor 😢 
![image](https://github.com/airbnb/visx/assets/47266830/29c3de9f-43f8-4624-9f31-ddf4a7863da9)

**Comment by RamonEspinosa** [comment]
I found the issue is that the x axis is using a `scalePoint`. I'm now unsure if this is a bug or if this behaviour is expected.

**Comment by hshoff** [comment]
Hi @RamonEspinosa, yes that would be expected behavior for scalePoint. For this example, I'd recommend using `scaleTime` and update the data `x` to `new Date()` and set the number of ticks on the bottom axis.

https://github.com/airbnb/visx/assets/339208/fdce26ee-043e-47aa-a65c-ae128228d3bb

[Example](https://codesandbox.io/p/sandbox/visx-nearest-datum-bug-forked-kvjgh6?file=%2Fsrc%2FApp.tsx%3A29%2C14&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu3gbn1b00063b6ovrkkqr9q%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu3gbn1b00023b6ob9o0nj1l%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu3gbn1b00033b6o44oxtj9x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu3gbn1b00053b6oaciyw69f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu3gbn1b00023b6ob9o0nj1l%2522%253A%257B%2522id%2522%253A%2522clu3gbn1b00023b6ob9o0nj1l%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu3h8nxk00023b6oc56eipxm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A29%252C%2522startColumn%2522%253A14%252C%2522endLineNumber%2522%253A29%252C%2522endColumn%2522%253A14%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clu3h8nxk00023b6oc56eipxm%2522%257D%252C%2522clu3gbn1b00053b6oaciyw69f%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu3gbn1b00043b6o366ism9e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu3gbn1b00053b6oaciyw69f%2522%252C%2522activeTabId%2522%253A%2522clu3gbn1b00043b6o366ism9e%2522%257D%252C%2522clu3gbn1b00033b6o44oxtj9x%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu3gbn1b00033b6o44oxtj9x%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

```ts
interface Datum {
  x: Date;
  y: number;
}
const data: Datum[] = [
  {
    x: new Date(2023, 0, 1),
    y: 10,
  },
  {
    x: new Date(2023, 2, 1),
    y: 2,
  },
  {
    x: new Date(2023, 3, 1),
    y: 7,
  },
  {
    x: new Date(2023, 4, 1),
    y: 3,
  },
];

// ...

  xScale: {
    type: "time",
  },

// ...

<Axis orientation="bottom" numTicks={4} />
```

**Comment by RamonEspinosa** [comment]
> Hi @RamonEspinosa, yes that would be expected behavior for scalePoint. For this example, I'd recommend using `scaleTime` and update the data `x` to `new Date()` and set the number of ticks on the bottom axis.

Thank for replying! 
I ended up switching to a time scale and it works perfectly!
