### ISSUE TITLE
Tooltip with an arrow

### ISSUE THREAD

**Issue by nouman91** [airbnb/visx#1811]
Is there any way to add an arrow style to the tooltip? I am looking for something similar to this:

https://popper.js.org/docs/v2/modifiers/arrow/

I have looked through the documentation & issues logged, I have not found anything on it. Any help on this is greatly appreciated.

**Comment by nouman91** [comment]
@williaster, thank you for replying. I ended up using mui popper for my needs. Would you mind explaining the tooltip positioning in visx in detail? My experience suggests that placing tooltips at a specific point doesn't work reliably with visx. 

My use case:
I am building a simple vertical bar graph that needs tooltip at top of the bar. I was not able to achieve this with visx. Tooltip Following is the quick demo that I put together:

https://codesandbox.io/p/sandbox/wonderful-darkness-kjz784?file=%2FExample.tsx%3A106%2C38


Looking forward to your reply

**Comment by nouman91** [comment]
@williaster whenever you get a chance please check my above comment & let me if my assumption is correct. This is what I wanted & I could not get the desired result with visx
<img width="1335" alt="Screenshot 2024-03-19 at 4 40 57 PM" src="https://github.com/airbnb/visx/assets/17067898/d063e4a3-1efb-4e82-92a9-e268dbe75b56">

**Comment by hshoff** [comment]
Hi @nouman91 I went to check out your link and codesandbox says 404 not found. 

Happy to take a look. The problem you described sounds like the graph container is missing a `position: relative` but hard to say without looking at an example

**Comment by nouman91** [comment]
Thank you @hshoff here is the Sanbox link:

[Sanbox](https://codesandbox.io/p/sandbox/wonderful-darkness-kjz784?file=%2FExample.tsx%3A106%2C38)

Please note it's just a modification of examples from your code base.

**Comment by hshoff** [comment]
I see you've added a `<div style={{ padding: 200 }} />` within the chart component.

This breaks the layout position of the tooltip as you said. Adding a div with padding within the chart adds height but doesn't include the additional height when calculating the chart bounds.

Instead of adding a div with padding within the chart, you'd want to update `margin.top` to `400` (the 200px padding for top and bottom).

```js
const defaultMargin = { top: 400, left: 50, right: 40, bottom: 100 };
```

This will make sure to include the offset in the bounds

```js
const xMax = width - margin.left - margin.right;
const yMax = height - margin.top - margin.bottom;
```

Alternatively, you could move the div with padding outside of the chart component and into index.tsx above the `<ParentSize>`.

```jsx
root.render(
  <>
    <div style={{ padding: 200 }} />
    <ParentSize>
      {({ width, height }) => <Example width={width} height={height} />}
    </ParentSize>
  </>
);
```

Another way to solve this would be to offset the tooltip position to include the padding.

```jsx
const padding = 200;
// ...
<div style={{ padding }} />
// ...
<Tooltip
  top={tooltipTop + padding * 2}
  left={tooltipLeft}
  style={tooltipStyles}
>
```

My recommendation would be to update the margin or move the div with padding outside the chart component. But it depends on what you're trying to do. Hope this helps and thanks for checking out visx.

**Comment by nouman91** [comment]
Thank you @hshoff I like the ParentSize approach I will give this a short
