### ISSUE TITLE
Visx Pie Chart no way to make it 3d

### ISSUE THREAD

**Issue by tempoeric** [airbnb/visx#1832]
Hi I encounter an issue, is there no way for the pie to be a 3d model or make it fat not a flat pie chart. It would be better if we could do it like this. Any help regarding this matter would be appreciated.

![image](https://github.com/airbnb/visx/assets/42777871/cf851705-07d0-4d7c-a660-ced67d6f0a3b)

**Comment by hshoff** [comment]
Hi @tempoeric, that's correct visx doesn't support 3d pie charts.

**Comment by kristw** [comment]
@tempoeric Thank you for your suggestion. We appreciate your input and your interest in enhancing visx.

However, 3D pie charts are widely recognized as an anti-pattern in data visualization. They tend to misrepresent information due to the distortions and perspective issues inherent in their design.

As practitioners in the field of data visualization, we are committed to improving public data literacy and promoting best practices. We believe that supporting 3D pie charts would not align with this goal and have no plan to support this.

For more information on the drawbacks of 3D pie charts.
* https://medium.com/@purohitpraveen/data-vizualization-why-3d-charts-are-a-terrible-idea-32657fbb928e#:~:text=In%20the%203D%20chart%2C%20on,the%20principle%20of%20perspective%20distortion.
* https://community.tableau.com/s/question/0D58b0000BVu3bmCQB/3d-pie-chart-in-tableau
* https://flowingdata.com/2012/06/15/what-3-d-pie-charts-are-good-for/
* https://www.data-to-viz.com/caveat/3d.html
