### ISSUE TITLE
Sparklines from data-ui and latest version of vx

### ISSUE THREAD

**Issue by alangrn** [airbnb/visx#794]
Is there any plan to migrate the sparklines in data-ui to the latest version of vx?

**Comment by williaster** [comment]
Duplicates [`data-ui` #204](https://github.com/williaster/data-ui/issues/204) 

A sparkline is almost the same as an `XYChart` with some convenience utilities like min/max labels. Because they are so similar, there is currently no plan to migrate it. If it's a major feature request we could likely add the missing convenience functionality to the [upcoming `xychart`](https://github.com/hshoff/vx/projects/3) package.

**Comment by bonesoul** [comment]
hey @williaster is the work already done?

**Comment by williaster** [comment]
xychart is published / fully-featured, yes
