### ISSUE TITLE
Dynamic time series axis

### ISSUE THREAD

**Issue by alangrn** [airbnb/visx#809]
Does the time series axis for Visx change dynamically or does the suer need ot enter the number of ticks?

For example here :https://bl.ocks.org/robyngit/89327a78e22d138cff19c6de7288c1cf

I have a chart with 100 data points so can render the chart but the labels overlap. DO I need to replicate the logic as per the above in my chart or do I need to build something similar as the linked attached?

**Comment by williaster** [comment]
If you pass nothing to an `Axis` component, it will use the default number of ticks for the `scale` you use (which varies by scale type, e.g, a `band` scale will render a tick for every single value [because it should] whereas a time or numeric scale will not).

For everything except `band` scales, you can specify [`numTicks`](https://airbnb.io/visx/docs/axis#Axis_numTicks) for your `Axis` or for any scale type you can specify [`tickValues`](https://airbnb.io/visx/docs/axis#Axis_tickValues).
