### ISSUE TITLE
[axis] tick label rotation?

### ISSUE THREAD

**Issue by alangrn** [airbnb/visx#810]
Any plans to implement something like  axisLabelRotate as pr the example here:
https://blog.scottlogic.com/2019/05/09/building-a-better-d3-axis.html

https://github.com/d3fc/d3fc/tree/master/packages/d3fc-axis

https://github.com/d3fc/d3fc/blob/master/packages/d3fc-axis/src/axisLabelRotate.js

**Comment by williaster** [comment]
From a vis best-practice point of view I would recommend **against** rotated axis tick labels because they are harder for you viewers to read. First I'd consider
- if it's for x-axis labels, is it possible to make the x-axis a y-axis which handles long labels better because there is more space
- if it has to be an x-axis, can you reduce the number of tick labels (e.g., for a time or log scale) so there is more room for non-rotated labels?

Otherwise, we do already support this by passing an `angle` value in `tickLabelProps` for `@visx/axis`. This is passed to `@visx/text`, which does the right thing

https://codesandbox.io/s/stoic-https-5uv3i?file=/Example.tsx

![image](https://user-images.githubusercontent.com/4496521/94221048-31624380-fe9f-11ea-8883-662c8d0f44d1.png)
