### ISSUE TITLE
@visx/xychart has not been published on NPM registry

### ISSUE THREAD

**Issue by grsoares21** [airbnb/visx#854]
I've noticed this when I've tried to run the demo app and I couldn't run install because the @visx/xychart was not being found on the registry. At first I thought it was a typo in the package.json, but indeed it doesn't seem to have been published.

https://www.npmjs.com/search?q=xychart
https://www.npmjs.com/search?q=visx
https://www.npmjs.com/package/@visx/xychart

**Comment by williaster** [comment]
Hey @grsoares21 👋  thanks for checking out `visx`. `@visx/xychart` is not yet published because it's not quite fully featured enough and is still under heavy development (see the [XYChart project](https://github.com/airbnb/visx/projects/3)) so breaking API changes are expected.

This shouldn't break local development, though. how are you installing packages? Per the [`CONTRIBUTING.md`](https://github.com/airbnb/visx/blob/master/CONTRIBUTING.md#local-development), you should

```sh
# install dependencies in the monorepo root
# `yarn` will symlink between-package dependencies instead of installing from the `npm` registry
yarn

# build packages and generate types for local development
yarn build
```

Then for [running demo pages](https://github.com/airbnb/visx/blob/master/CONTRIBUTING.md#running-demo-pages) you should `cd packages/visx-demo && yarn dev` to start the demo `next.js` app on `localhost:3000`.

I'm going to close this because it currently works for me, but feel free to re-open if you're still having problems 🙌

**Comment by grsoares21** [comment]
Ah ok. Sorry for the false alarm then. Thanks for the clarifications. It was my mistake indeed.
