### ISSUE TITLE
Support for framer-motion and other libs that wrap HTML Elements

### ISSUE THREAD

**Issue by ConneXNL** [airbnb/visx#862]
I want to use framer-motion to animate visx elements. However, framer-motion (and also other libraries like react-spring) wrap the HTML Dom elements with their own function, for example:

```
import { motion } from 'framer-motion';
<svg><motion.text>My Text</motion.text></svg>
```

instead of 
`<svg><text>My Text</text></svg>`

visx however doesn't allow you to overwrite the internal dom elements it is using. For example the `<Text/>` component always renders a `<text/>` dom element:
https://github.com/airbnb/visx/blob/master/packages/visx-text/src/Text.tsx#L220

It would be great if 'text' is the default and the `<Text/>` component would get an "as", "component" or "element" prop that would allow us to overwrite the internal component that it renders, to for example {motion.text}.

It seems `<Axis>`' labelProps already allows us to push props to the inner `<Text/>` component it is using so that would also allow us to overwrite the component from a parent.

Other components that render different svg elements like paths or lines could also use this method.

**Comment by williaster** [comment]
Hey @ConneXNL 👋  thanks for checking out `visx`. we've made a few passes at components in various packages to support the child render props pattern, where the developer can override the rendering logic by passing their own `children` function:

```tsx
// default rendering
<BarStack {...} />

// override completetly
<BarStack>
  {stacks => (
     // custom logic
  )}
</BarStack>
```

We've done this for many packages, especially `@visx/shape`, but not comprehensively across all packages. If there are specific components or packages you have noted as missing this override we are definitely open to fixing them or reviewing PRs. 

Regarding `Text` specifically, depending on what you need you could use the [approach that `@visx/react-spring` uses](https://github.com/airbnb/visx/blob/master/packages/visx-react-spring/src/axis/AnimatedTicks.tsx#L60), which is to animate a wrapper `<g />` element rather than the `Text` itself. `Text` does a lot of work with `tspan`s to correctly apply y-offsets to wrapped text, so that would need to be mirrored by an child render override and would be more complex.  

```tsx
<svg>
  <motion.g>
    <Text>My text</Text>
  </motion.g>
</svg>
```

Hope that helps.

**Comment by williaster** [comment]
Also see more on render props here #383

**Comment by williaster** [comment]
Going to close this issue for now, feel free to re-open it if more specific questions or limitations come up 👍
