### ISSUE TITLE
Using visx for Figma-like React application

### ISSUE THREAD

**Issue by devinhalladay** [airbnb/visx#875]
Hi!

I hope this is an alright place to ask a high level question about a visx use case. 

I know visx is intended for more traditional information visualization, but I'm hoping it can help me solve a set of interaction problems in a Figma-like application that has data-backed layers (they can be text, images, embeds, and more complex React elements).

I am working on an application that is essentially an end-user interface for a relational database: you can imagine it like Figma, but with data-backed layers. It has a canvas (the concept, not the HTML5 one!) that can pan and zoom, and "blocks" (react elements) that can be dragged around, selected, and undergo state changes based on actions performed on a selected block. There may be a few blocks on the canvas, or all the way up to to hundreds or more.

Currently I've got a number of libraries awkwardly strung together to make all this functionality happen, but I'm wondering if visx could offer the tools I need to accomplish that type of UI and interaction set? Do any of the devs on this project have a perspective to offer on my use case?

EDIT: I am hoping I can string together `@visx/drag`, `@visx/zoom`, and `@visx/brush` to accomplish: draggable blocks, a zoom/pan canvas, and multi-block selection, respectively. In the future I would like to provide users with different "views" of their database, so having the rest of the visx toolkit at my disposal is a big reason I'd love to be able to use visx as my figma-canvas-like interaction library.

Thank you <3

**Comment by williaster** [comment]
Hey @devinhalladay 👋  thanks for checking out `visx`. This sounds pretty interesting, our general recommendation would be to give it a shot (with `@visx/zoom,drag,brush` as you mentioned) and if you run into issues or limitations to please open issues or PRs for us 👀 

I would say that HTML hasn't been a major focus for us just yet (most packages were built with SVG in mind), so there may be a few kinks to iron out there. For instance #807 was recently opened and highlighted that Zoom does not work with HTML elements right now because of how the `transform` is implemented (see 💬  in the issue). But that should be fixable (I won't have bandwidth for that for a few weeks but definitely happy to review PRs in the mean time).

Hope that helps! 🚀

**Comment by devinhalladay** [comment]
Great, thanks so much for the thoughtful reply @williaster! I've had some bad experiences with repo maintainers lately so that was refreshing :)

I'll definitely give it a shot. Would you prefer I close this issue or keep it open to post any updates / refer to any PRs I write?

**Comment by williaster** [comment]
Thanks @devinhalladay ! We try to be friendly here and just want `visx` to have a positive, productive community 😄 

Maybe let's close the issue for now, and then if issues come up you can either create new issues / reference this one, and / or re-open this one.
