### ISSUE TITLE
Testing approaches in this project

### ISSUE THREAD

**Issue by m0t0r** [airbnb/visx#918]
@williaster @hshoff I have a few questions about testing approaches in this project. I understand Airbnb probably has its coding tools standards but I was wondering how strict they are ? :) For example, would it be possible to migrate from enzyme to a much better [Testing Library](http://testing-library.com/). I also noticed use of shallow rendering in tests which is [not the best approach](https://kentcdodds.com/blog/why-i-never-use-shallow-rendering). There is also [cypress-react-unit-test ](https://github.com/bahmutov/cypress-react-unit-test)which for projects like `visx` could be a nice option to consider as well, maybe not for all but some of the interactive tests because it renders in real browser. Could you share your thoughts ?

**Comment by williaster** [comment]
Hey @m0t0r thanks for creating this issue 🙏   (and sorry about the complexities of this as it relates to the `react@17` upgrade in #872)

Generally Airbnb is moving toward using `react-testing-library` (which you've linked to), so I think we are supportive of moving in that direction for `visx` over enzyme. Currently I'm not sure we have the bandwidth to do this migration ourselves, so I'll tag this issue with `👋  help wanted`. If you or others are interested in helping with this we would happily review any PRs 👀 .

As far as cypress / visual testing, we are planning to add screenshot testing with [happo](https://happo.io/) 🦛  soon (my plan is before end of 2020) for the `demo` package so that we can better-detect visual changes.

Not sure if @hshoff has any other thoughts to add.

**Comment by m0t0r** [comment]
Hi @williaster, great, thanks for your reply, I appreciate. Yes, migrating to `react-testing-library` may take quite a bit of efforts. I will try to start looking into that and maybe get an initial plan.

**Comment by hshoff** [comment]
My preference would be to wait for the official [enzyme 17 adapter](https://github.com/enzymejs/enzyme/issues/2429#issuecomment-713251132). Migrating the entire test suite to `react-testing-library` should be a separate discussion vs supporting react 17 as a peerDep.

**Comment by whitetiger1399** [comment]
@hshoff  are you also planning to use `jest` for testing?

**Comment by williaster** [comment]
We currently use `jest` for unit tests and I think this would be true even if we moved to `react-testing-library` since `jest` provides the runner + the assertion framework, not the `react` manipulations.

Also an update, we now use happo for visual testing of all gallery examples as added in #1030
