### ISSUE TITLE
[@visx/text]: wordsByLines length differs in enzyme versus browser

### ISSUE THREAD

**Issue by susiwen8** [airbnb/visx#942]
When run `Does not wrap text if there is enough width` with enzyme, it shows  that `wordsByLines` equal to ` [ { words: [ 'This', 'is', 'really', 'long', 'text' ], width: 240 } ]`.  `wordsByLines` has one item.

But when I run it on browser 
<img width="343" alt="Screen Shot 2020-11-22 at 22 21 32" src="https://user-images.githubusercontent.com/20318608/99906292-357cd700-2d11-11eb-81a3-c48b5cb6b1b2.png">
<img width="351" alt="Screen Shot 2020-11-22 at 22 21 58" src="https://user-images.githubusercontent.com/20318608/99906295-37469a80-2d11-11eb-8c1e-2928b2f264b5.png">
`wordsByLines` has two items.

Also, does `@visx-text` have plan to rewrite with hook? I'm happy to submit a PR to rewrite it.

**Comment by williaster** [comment]
Hi @susiwen8  👋  thanks for checking out `visx`. 

I think that this difference is likely due to `getBoundingClientRect` defaulting to `width: 0` in a testing environment, which means it would likely wrap for every new word. We mock out `Element.prototype.getBoundingClientRect` in some cases for our own `visx` tests (e.g., in [`@visx/responsive`](https://github.com/airbnb/visx/blob/db9c81e130d24a9f1ea72156caaf7465f41cc157/packages/visx-responsive/test/withParentSize.test.tsx#L9)), so you might try that to see if it helps.

Regarding a `useText` hook or similar, we don't currently have that but it seems like a great idea and I'm happy to review a PR if you are interested! (we could open up a separate issue to track if you want)

**Comment by susiwen8** [comment]
> Regarding a useText hook or similar, we don't currently have that but it seems like a great idea and I'm happy to review a PR if you are interested! 

Sure I'll do it sometime in this week. @williaster
