### ISSUE TITLE
non continuous date domain

### ISSUE THREAD

**Issue by harvey56** [airbnb/visx#943]
Hello,

I have a non-continuous date domain to feed a bar and line chart. To be more specific, I have no data for the weekend and no data for the evening. With a scaleTime, when I hover over the chart, my tooltip will jump from friday to monday, with no tooltip to show in between on the chart. That makes tooltip data feel counter intuitive and "buggy" when hovering. 

Therefore, I'd like to filter out the tickValues not present in my x data feed (= the x axis labels should not show saturday, sunday), and so when I move the cursor from left to right over the chart, the tooltip appears continuously. 

How to do that ? I'm guessing I may need to change scaleTime to another scale. What about the tooltip ?

**Comment by williaster** [comment]
Hey @harvey56 👋  thanks for checking out `visx`.

Generally if you are using a `scaleTime `, the intervals between ticks must be constant. You could consider a `scaleBand` to only include values for which you have data (e.g., week days), but this can be misleading for an axis that appears to plot time because people generally expect points to be evenly spaced, as `scaleTime` behaves.

Another option would be for you to add `null` values to the weekend points, so that a tooltip would not jump from friday <> monday, and for weekends could simply show `null` or something. Hope this helps.

**Comment by williaster** [comment]
Going to close this now as it's more of a question. Feel free to reopen if you think there's a visx issue or feature missing.
