### ISSUE TITLE
Testing with visx imports renders empty div

### ISSUE THREAD

**Issue by EfosaSO** [airbnb/visx#951]
When testing using `@testing-library/react` it renders a div like so:

`<div style="width: 100%; height: 100%;" />`

I thought it might be a resizing issue as the component is wrapped with a `withParentSize` hoc and when I remove that it complains about needing a Resize-observer polyfill

`Error: Uncaught [Error: This browser does not support ResizeObserver out of the box. See: https://github.com/react-spring/react-use-measure/#resize-observer-polyfills]`

Haven't found anything on the net about testing components with `visx`

**Comment by williaster** [comment]
Hey @EfosaSO 👋  thanks for checking out `visx`. Can you link to or provide more code examples for what you are rendering?

`visx` is just `react`, so there is nothing "special" about testing it versus normal `react` (we use `enzyme` currently for our tests, but `react-testing-lib` works fine assuming you have the needed polyfills [which depend on components you are using]). What you are seeing is do to how the components you are using work.

`withParentSize` [wraps your component in a `div`](https://github.com/airbnb/visx/blob/master/packages/visx-responsive/src/enhancers/withParentSize.tsx#L80) in order to measure the parent's container size using a `ref` (that's the `div` you are seeing). if your component never mounts, or if `getBoundingClientRect` is not mocked out in your testing environmemt (e.g., jsdom), it will never render its children and so that may be why you are just seeing a `div`. You could also try [`ParentSize`](https://github.com/airbnb/visx/blob/master/packages/visx-responsive/src/components/ParentSize.tsx) instead of the HOC as it should always render its children.

`withParentSize` (and `ParentSize`) also currently import a global polyfill for `ResizeObserver`, so when you remove it you no longer get that polyfill. It looks like you are getting an error from `react-use-measure` which likely means you are using `@visx/tooltip` or `/annotation` which use that library. [Both of the readmes for those packages specify](https://github.com/airbnb/visx/tree/5cd287f5c446297d9ace29675db385507895caa4/packages/visx-tooltip#%EF%B8%8F-resizeobserver-dependency) that they have a dependency on `ResizeObserver`, and so you must either pass the polyfill yourself, or import one globally (as the `@visx/responsive` components do).

**Comment by EfosaSO** [comment]
@williaster thanks for that thorough explanation. I will first try your solutions and report back with a link to my implementation if I run into issues.

**Comment by EfosaSO** [comment]
@williaster switching to `ParentSize` solves the issue once you add a `ResizeObserver` pollyfill

**Comment by williaster** [comment]
Glad to hear! Going to close this for now, feel free to re-open if you have any further questions/problems!

**Comment by SethTompkins** [comment]
Hey, I am seeing this issue when trying to test a component that uses `XYChart`, it only renders `<div style="width: 100%; height: 100%;" />` in the test if you do not specify a width & a height to the component (it wraps itself in `ParentSize` if one of those is not passed).

Also using `@testing-library/react`, and have made sure to set the `ResizeObserver` polyfill in my test setup
```
import ResizeObserver from 'resize-observer-polyfill';
window.ResizeObserver = ResizeObserver;`
```

**Comment by williaster** [comment]
Hey @SethTompkins I think it may be challenging to test `XYChart` without providing `width`/`height`. even if `ResizeObserver` is available, it will rely on `Element.prototype.getBoundingClientRect()` which I believe returns `0` width and height in a `jsdom` environment. 

You could try mocking that out to return non-zero dimensions, but it may be easiest to pass through the `width`/`height`. If it's useful, you can check out the [tests we have for `XYChart`](https://github.com/airbnb/visx/blob/master/packages/visx-xychart/test/components/XYChart.test.tsx) itself (uses enzyme not react testing lib, but should be similar).

**Comment by SethTompkins** [comment]
Ah that makes sense, I will just feed it width/height for testing. Thanks!

**Comment by ddanielcruzz** [comment]
Hey @williaster I'm also getting an empty div with when testing a component

My test 
```js
describe('CandleStickChart', () => {
  it('should render successfully', () => {
    const formattedData = formatCandleChartData(data, accessors);
    const { baseElement, debug } = render(

      <CandleStickChart
        data={formattedData}
        parentHeight={500}
        parentWidth={500}
      />
    );
    expect(baseElement).toBeTruthy();
    debug();
  });
});
```
Here's how I'm exporting my component
```js
export const CandleStickChart = withParentSize(
  withTooltip(InnerCandleStickChart)
);
```

From what I understood, passing the height and width should render the children. Or maybe I got it wrong, hope you can assist me. 😄
