### ISSUE TITLE
Suggestion: Prop for AreaClosed to specify in which direction area gets closed

### ISSUE THREAD

**Issue by puchm** [airbnb/visx#954]
I don't know if this is the right place to put this but I have a suggestion for the AreaClosed component.

It seems like it always uses the corner in the bottom left to close the area.
Here's a screenshot of the current behaviour:

![image](https://user-images.githubusercontent.com/21011840/100758977-67b4c580-33f0-11eb-9152-ef48e8b3005a.png)

You can see that the AreaClosed (light blue area) gets closed using the corner in the bottom left. It basically draws a line from the last data point on the x axis downwards, then left until it reaches the start of the x axis, then to the first data point on the x axis.

However, I would like a prop that allows me to do it the other way around: From the last point on the X axis it should go all the way up, then to the first point on the x axis in order to close the area. So basically I want the AreaClosed to fill the exact opposite of what it is filling right now.

A way to implement this could be to use a prop that specifies which direction the AreaClosed fills up.

Also, is there any other way to achieve this right now? I tried doing it by passing a flipped yScale to the AreaClosed and also making the y accessor "flip", but that seems like a pretty hacky solution.

**Comment by williaster** [comment]
Hey @puchm 👋  thanks for checking out `visx`.

Turns out this functionality is actually already supported with the `AreaClosed` component in `@visx/shape`, using the `y0` prop (which mirrors the [`d3-shape`](https://github.com/d3/d3-shape#areas) behavior). Typical area chart use-cases need `y0` set to the lower bound of the y-axis, so that's the default behavior but you can pass in a `number` or `(d: Datum) => number` accessor function to alter the behavior as noted in the [documentation](https://airbnb.io/visx/docs/shape#Area).

I noticed we have a bug for setting this value to `0` (fix coming shortly), but for now you could just pass a function which always returns `0`. [Here's a sandbox demo](https://codesandbox.io/s/nostalgic-villani-340xw?file=/Example.tsx) to illustrate. Note that the value returned needs to be in svg coordinate space, where `y=0` is at the top.

<img src="https://user-images.githubusercontent.com/4496521/100818098-4b1f8a00-33fe-11eb-84c1-0f028910d1d5.gif" width="500" />

I'd note that the lower-level `Area` shape (on top of which `AreaClosed` is implemented) gives you even greater control over `x0, x1, y0, y1` so that you can implement things like [streamgraphs](https://airbnb.io/visx/streamgraph).

Hope that helps! Going to leave this open until the fix for `y0={0}` lands.
