### ISSUE TITLE
The Text component renders wrapped in its own svg element.

### ISSUE THREAD

**Issue by boberbober** [airbnb/visx#971]
If you follow the example code from [the Text component docs page](https://airbnb.io/visx/docs/text) and use it like this:

```javascript
const App = () => (
  <svg>
    <Text verticalAnchor="start">Hello world</Text>
  </svg>
);
```

You will get:

```html
<svg>
  <svg x="0" y="0">
    <tspan>Hello world</tspan>
  </svg>
</svg>
```

I'm not sure if this is the desired way the component should work or the example is wrong. I expected the `<Text>` component to render a `<tspan>` that I can use in my own `<svg>` parent with other elements.

Edit: Nevermind... I realized it is proper syntax to use svg inside svg and this is how it should work. Please remove this issue.

**Comment by williaster** [comment]
Hey @boberbober 👋  thanks for checking out `visx`. Just to clarify for any future folks who stumble upon this, `Text` is implemented by rendering a separate `svg` as you note. This is **intentional** as it simplifies positioning, rotation, and scaling.

Note that it is **valid** to render nested `svg`s.
