### ISSUE TITLE
@visx/text: how to do 2-line text?

### ISSUE THREAD

**Issue by bebbi** [airbnb/visx#980]
In a sunburst chart built from `arc`s, I position a `<Text />` next to every arc using these props:

```
// const [centroidX, centroidY] = arc.centroid()
<Text x={centroidX}, y={centroidY}, angle, width, scaleToFit, textAnchor="middle", verticalAnchor="middle">
```

I don't seem able to construct a 2-line text with a label (line 1) and a size (line 2).

- If I try `dy="1em"`, the y-axis doesn't take into account the rotation.
- If I try nesting `tspan`s, it renders as `[object object]`

Am I missing a straightforward approach without having to calculate `em`'s manually?

(..which allows using a different font-size on line 2.)

**Comment by williaster** [comment]
Hey @bebbi thanks for checking out `visx`, sorry for the delay in response (holidays ... 🎁 ).

The `@visx/text` `<Text />` component currently wraps based on the `width` prop alone (i.e., it will wrap if the text cannot fit on one line within the specified `width`), so you cannot currently force wrapping onto two (or more) lines. 

> If I try `dy="1em"`, the y-axis doesn't take into account the rotation

Yes, currently the `dx/dy` offsets are applied as translations on the `<Text />` `svg`, and don't take into account the `angle`. This seems like a limitation but I could see arguments for both types of behavior. For now I think you'd need to compute the angle-corrected offsets yourself. If you are interested in adding this functionality to the package itself I'd happily review it!

> If I try nesting tspans, it renders as [object object]

`<Text />` expects `children` to be a `string`, which is why a `tspan` is coerced to `[object object]`. 

<hr />

There has been discussion of improved functionality in the past to force line breaks #644, but if you want to use two different styles/font-sizes, I think you'll have to render two separate `<Text />`s. Wrapping is computed based on font-size and styles, so having one component do multiple width calculations for multiple styles would get overly complex. 

Three possible solutions for you come to mind:
1) you could be use the relatively new [`useText ` hook](https://github.com/airbnb/visx/blob/master/packages/visx-text/src/hooks/useText.ts) which `<Text />` is implemented with. If you invoke this once for each line of text, you could use different styles for each and base the y-offset of the second line on the total computed height of the first.
2) The `@visx/annotation` `Label` component renders a `title` and `subtitle` with different styles with stacked offsets (see demo [here](https://airbnb.io/visx/annotation)). It is implemented with `react-use-measure`, [offsetting the `subtitle` based on the bounding box of the rendered `title`](https://github.com/airbnb/visx/blob/master/packages/visx-annotation/src/components/Label.tsx#L201).
3) `SVG` text is complicated 🙉  , and for this reason we have chosen to use `html` text in several `visx` packages (tooltip, legend) to get easy wrapping and layout for free. You could think about rendering your arc labels _**inside [React Portals](https://reactjs.org/docs/portals.html)**_, meaning that you could render them as a child React component in your Chart, but they'd be rendered inside of a separate `div` on the page (i.e., not as an `SVG` child). The [`useTooltipInPortal` hook](https://github.com/airbnb/visx/blob/master/packages/visx-tooltip/src/hooks/useTooltipInPortal.tsx) does exactly this so you might even be able to use it out of the box (it handles page x/y offsets including scroll position, which you'll have to do otherwise)

**Comment by whitetiger1399** [comment]
I tried using `\n` and `\r\n` and they also didn't work. Can we have the support of new line feed in  <Text />

**Comment by bebbi** [comment]
Thanks a lot @williaster for that extensive answer. We've favored 1 and 3, and so far 1 has worked fine for us.
